### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [nerney/dappy#2]
Hello! @nerney 

Hello! @monch1962 I wanted to contribute. That's why, i designed a logo for dappy. I have combined a  Authenticator and the first letter of the software. What do you think? I will wait for feedback.

Have a nice day!

![dappy](https://user-images.githubusercontent.com/36298335/42698595-0a2722a6-86c7-11e8-9874-aeb782f0db34.jpg)

**Comment by nerney** [comment]
wow, awesome!
i personally like the blue one the best.
thanks!

**Comment by reallinfo** [comment]
Oh, okay. I sent a pr. (blue version and all files.) Please check it

https://github.com/nerney/dappy/pull/3

**Comment by stefanb** [comment]
PR #3 was closed after c07537d was merged. I suggest to close this issue as well.
